import { Geist, Montserrat, Oswald } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import ScrollWrapper from "@/scrollWrapper/scrollWrapper";
import Preloader from "@/components/Preloader";
import GlobalTransition from "@/components/GlobalTransition";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Montserrat({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bodoniModa = Oswald({
  variable: "--font-bodoni-moda",
  subsets: ["latin"],
});

export const metadata = {
  title: "GAMESTA",
  description: "Generated by SHAN",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${bodoniModa.variable} h-full antialiased no-scrollbar`}
    >
      <head>
          <Script id="scroll-restoration" strategy="beforeInteractive">
            {`
            if ('scrollRestoration' in history) {
              history.scrollRestoration = 'manual';
            }
          `}
          </Script>
      </head>
      <body className="min-h-full flex flex-col">
        <ScrollWrapper>
          {/* <GlobalTransition /> */}
          <Preloader />
          {children}
        </ScrollWrapper>
      </body>
    </html>
  );
}
